language: cpp

branches:
  except:
  - gh-pages
  - /.*appveyor.*/

env:
  global:
  - GH_REPO_NAME: libossia
  - GH_REPO_REF: github.com/OSSIA/libossia.git
  - secure: "fHuSuq9OJbvmdb4bSKUenCpmJ3XtYtX9xa+dUncxVbwwGJ02K/OrQ594ON5+vK5AL/co8aOx6e5FdZ4lRyFJglevE4Qn0A6LPdH7RoORk3xZWr34BoBQWYCGykBezEu+AIIic8SFfgE2gP0fPmz9IWcEEDgQTuckLVr6DdjLkQw="
  - ARTIFACTS_DIR: ${TRAVIS_BUILD_DIR}/artifacts


osx_image: xcode9
dist: trusty
sudo: required

# That was for RpiDocker build
# service:
# - docker

matrix:
  exclude:
  - os: linux
  - os: osx
  
  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 BUILD_TYPE=python_manylinux

  - sudo: required
    services:
      - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 BUILD_TYPE=python_manylinux
         PRE_CMD=linux32

# work around https://github.com/travis-ci/travis-ci/issues/8363
before_script: pyenv global $TRAVIS_PYTHON_VERSION

before_install: travis_wait 30 "./ci/deps.sh"

script: "./ci/build.sh"

deploy:
  - provider: releases
    api_key:
      secure: cuMgjuaFGGh7YxpIMP7dLyTzzRkAK6q1//5qZ1wHrnEjwtZK4+XRqQP4uQNCJsk22yrc9iu7AcJ9xsZ72xs3C4EXPLa7GlWLKrQD1M7J4viaZCb1AKiEjFYMEa6iRQf79ip7zDiWEQNV4aL+aJBZBLRZ4I8chvkKnUBaEOnVx6U=
    file_glob: true
    file: ${ARTIFACTS_DIR}/*
    skip_cleanup: true
    draft: false
    prerelease: false
    description: |+
      # Draft release of OSSIA $TRAVIS_TAG

      * All macOS packages are fat binaries that should work on macOS from 10.9 to 10.12 & later.
      * Packages ending in 'win32' are 32-bit, 'win64' are 64-bit and 'win' work on both architectures.
      * All Windows packages are built with VS2017.
      * Python packages are built with Python 2.7 and 3.4 on ubuntu 14.04, 2.7 and 3.6 version on macOSX.12 (from Homebrew) and 2.7 and 3.5 on Raspbian stretch.
      * QML packages are built with Homebrew's Qt version on macOS.
      * QML packages are built with Qt 5.9.1 VS2017 64 on Windows.
      * QML packages are meant to be put in the [QML Import Path](http://doc.qt.io/qt-5/qtqml-syntax-imports.html). For instance on macOS it should look like '/usr/local/Cellar/qt/5.9.1/qml/Ossia/qmldir'.

      Please consult [this wiki page](https://github.com/OSSIA/libossia/wiki/Integrations) to see what's here and what's missing.

      * [Documentation](https://ossia.github.io)
      * [Examples](https://github.com/OSSIA/libossia/tree/master/Documentation)
      * [Building from source](https://github.com/OSSIA/libossia/wiki/Building)
      * ***Do note use the Github source package ("Source code" link below) to build; instead do a git clone or use 'ossia-src-unix.tar.gz'. Else the build won't work due to Github not putting submodules in the archive.***

    on:
      repo: OSSIA/libossia
      tags: true
